Adding share button + fixing padding issue
tahiri-lab/iPhyloGeo pull request #13
Opened 2023-04-14 22:58 UTC by marc6981

2023-04-14 22:59 UTC, marc6981 reviewed
Good pour moi!

2023-04-15 13:58 UTC, jsDesm requested changes
Change les noms de variables et c'est chill

2023-04-15 13:58 UTC, jsDesm commented on apps/pages/results/result.py
> +    Output("dummy_share_result_output", "children"),  # needed for the callback to trigger
naming conventions

2023-04-15 13:58 UTC, jsDesm commented on apps/pages/results/result.py
> +    Input("share_result", "n_clicks"),
naming conventions

2023-04-15 14:36 UTC, lucavadnais commented on apps/pages/results/result.py
> +    Output("dummy_share_result_output", "children"),  # needed for the callback to trigger
Done !

2023-04-15 14:36 UTC, lucavadnais commented on apps/pages/results/result.py
> +    Input("share_result", "n_clicks"),
Done !

2023-04-15 15:16 UTC, merged